### ISSUE TITLE
Feature request: Pass input value to `onType` event

### ISSUE THREAD

**Issue by hognevevle** [Sitronik/vue3-beautiful-chat#1]
Thank you so much for porting this to Vue 3! 

I'd like to propose to pass the input value as a parameter to the `onType` event. In our case, we want to push this to our backend.

**Comment by Sitronik** [comment]
> Thank you so much for porting this to Vue 3!
> 
> I'd like to propose to pass the input value as a parameter to the `onType` event. In our case, we want to push this to our backend.

Your are welcome, I published version 3.0.2 with your changes 😉
