### ISSUE TITLE
Cannot read properties of null (reading 'scrollHeight')

### ISSUE THREAD

**Issue by utking** [Sitronik/vue3-beautiful-chat#4]
A simple scenario - a simple app with two routes - one with the chat and another without it. When you leave the page with the chat component, it throws an error
```
Uncaught TypeError: Cannot read properties of null (reading 'scrollHeight')
    at ResizeObserver.eval (vue3-beautiful-chat.umd.js:10:10950)
```
The ResizeObserver in https://github.com/Sitronik/vue3-beautiful-chat/blob/master/src/MessageList.vue#L132 is still there, while the $refs.scrollList is not.
Looks like ResizeObserver.disconnect() on unmount should solve the problem.

**Comment by utking** [comment]
> @utking Thanks for the issue, you can do PR wink

Sure, will do :)

**Comment by utking** [comment]
Please see https://github.com/Sitronik/vue3-beautiful-chat/pull/5 for a possible solution

**Comment by Sitronik** [comment]
> Please see #5 for a possible solution

Thanks 👍
